[project]
name = "adv-scripting-cloud"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.43.99",
]

[project.scripts]
adv-scripting-cloud = "adv_scripting_cloud:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
